/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    sessions: Session;
    characters: Character;
    episodes: Episode;
    scenes: Scene;
    tasks: Task;
    'prompt-templates': PromptTemplate;
    'prompts-executed': PromptsExecuted;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    scenes: ScenesSelect<false> | ScenesSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'prompt-templates': PromptTemplatesSelect<false> | PromptTemplatesSelect<true>;
    'prompts-executed': PromptsExecutedSelect<false> | PromptsExecutedSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'user' | 'admin' | 'producer';
  /**
   * User preferences and settings
   */
  preferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subscription?: {
    tier?: ('free' | 'pro' | 'enterprise') | null;
    maxProjects?: number | null;
    maxEpisodesPerProject?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Project ID reference
   */
  project: string;
  mediaType:
    | 'style_reference'
    | 'character_design'
    | 'environment_design'
    | 'concept_art'
    | 'storyboard'
    | 'video_segment'
    | 'audio_clip'
    | 'voice_profile'
    | 'music_track'
    | 'sound_effect'
    | 'final_video';
  /**
   * Whether this media was generated by an AI agent
   */
  agentGenerated?: boolean | null;
  generationMetadata?: {
    /**
     * ID of the agent that generated this media
     */
    agentId?: string | null;
    /**
     * Prompt used for generation
     */
    promptUsed?: string | null;
    /**
     * Version of the AI model used
     */
    modelVersion?: string | null;
    generationTime?: string | null;
    /**
     * Background task ID for tracking
     */
    taskId?: string | null;
  };
  /**
   * Jina v4 multimodal embedding vector
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Human or AI-generated description of the media
   */
  description?: string | null;
  /**
   * Array of tags for categorization
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relatedElements?: {
    /**
     * Character IDs featured in this media
     */
    characters?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Episode number if applicable
     */
    episode?: number | null;
    /**
     * Scene identifier if applicable
     */
    scene?: string | null;
    /**
     * Timestamp in seconds for video segments
     */
    timestamp?: number | null;
  };
  technicalData?: {
    /**
     * Duration in seconds for audio/video
     */
    duration?: number | null;
    /**
     * Resolution (e.g., 1920x1080)
     */
    resolution?: string | null;
    /**
     * Frames per second
     */
    fps?: number | null;
    /**
     * Audio sample rate in Hz
     */
    sampleRate?: number | null;
  };
  /**
   * Version number for iterative improvements
   */
  version?: number | null;
  status?: ('active' | 'draft' | 'archived' | 'processing' | 'failed') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  description?: string | null;
  genre: 'action' | 'comedy' | 'drama' | 'horror' | 'sci-fi' | 'thriller' | 'romance' | 'documentary';
  /**
   * Total number of episodes planned
   */
  episodeCount: number;
  targetAudience?: ('children' | 'family' | 'teen' | 'adult') | null;
  status: 'concept' | 'pre-production' | 'production' | 'post-production' | 'completed' | 'on-hold';
  /**
   * User who created this project
   */
  createdBy?: (string | null) | User;
  /**
   * Users who can edit this project
   */
  collaborators?: (string | User)[] | null;
  /**
   * Reference images for visual style
   */
  styleReferences?: (string | Media)[] | null;
  projectSettings?: {
    aspectRatio?: ('16:9' | '4:3' | '21:9') | null;
    /**
     * Target duration per episode in minutes
     */
    episodeDuration?: number | null;
    qualityTier?: ('draft' | 'standard' | 'premium') | null;
  };
  /**
   * Automated progress tracking
   */
  progress?: {
    currentPhase?:
      | (
          | 'story_development'
          | 'character_creation'
          | 'visual_design'
          | 'audio_design'
          | 'scene_production'
          | 'post_production'
          | 'final_assembly'
        )
      | null;
    /**
     * Array of completed workflow steps
     */
    completedSteps?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Overall completion percentage
     */
    overallProgress?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  /**
   * Project ID reference
   */
  project: string;
  user: string | User;
  /**
   * Current workflow step identifier
   */
  currentStep: string;
  /**
   * Array of chat messages and interactions
   */
  conversationHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current context for LLM processing
   */
  contextData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Whether system is waiting for user response
   */
  awaitingUserInput?: boolean | null;
  /**
   * Last set of choices presented to user
   */
  lastChoices?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sessionState?: ('active' | 'paused' | 'completed' | 'error') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: string;
  /**
   * Project this character belongs to
   */
  project: string | Project;
  name: string;
  description: string;
  profile?: {
    /**
     * Character age or age range
     */
    age?: string | null;
    /**
     * Character gender
     */
    gender?: string | null;
    /**
     * Array of personality traits
     */
    personality?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Character backstory and history
     */
    backstory?: string | null;
    /**
     * Array of character motivations and goals
     */
    motivations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    relationships?:
      | {
          /**
           * Related character
           */
          character?: (string | null) | Character;
          relationshipType?: ('family' | 'friend' | 'enemy' | 'romantic' | 'rival' | 'mentor' | 'other') | null;
          /**
           * Describe the relationship
           */
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  visualDesign?: {
    /**
     * Reference images for character design
     */
    referenceImages?: (string | Media)[] | null;
    /**
     * Final approved character design
     */
    finalDesign?: (string | null) | Media;
    /**
     * Style guidelines and notes
     */
    styleNotes?: string | null;
    /**
     * Array of hex color codes for character palette
     */
    colorPalette?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  voiceProfile?: {
    /**
     * ElevenLabs or other TTS voice ID
     */
    voiceId?: string | null;
    /**
     * Sample audio of character voice
     */
    audioSample?: (string | null) | Media;
    /**
     * Array of voice characteristics (pitch, tone, accent, etc.)
     */
    voiceCharacteristics?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Track character appearances across episodes
   */
  appearances?:
    | {
        episode?: (string | null) | Episode;
        /**
         * Array of scene IDs where character appears
         */
        sceneIds?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Total screen time in seconds
         */
        screenTime?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: string;
  /**
   * Parent project for this episode
   */
  project: string | Project;
  /**
   * Episode number in the series
   */
  episodeNumber: number;
  title: string;
  description?: string | null;
  synopsis?: {
    /**
     * One-sentence summary
     */
    logline?: string | null;
    /**
     * Full episode summary
     */
    summary?: string | null;
    /**
     * Array of themes explored in this episode
     */
    themes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'planning' | 'scripting' | 'storyboarding' | 'production' | 'editing' | 'completed';
  script?: {
    /**
     * Full script content
     */
    content?: string | null;
    /**
     * Script version number
     */
    version?: number | null;
    /**
     * Total word count
     */
    wordCount?: number | null;
    /**
     * Estimated duration in seconds
     */
    estimatedDuration?: number | null;
  };
  /**
   * Production progress tracking
   */
  production?: {
    sceneCount?: number | null;
    completedScenes?: number | null;
    /**
     * Overall render progress percentage
     */
    renderProgress?: number | null;
  };
  metadata?: {
    /**
     * Actual duration in seconds (after rendering)
     */
    duration?: number | null;
    /**
     * Final rendered episode video
     */
    finalVideo?: (string | null) | Media;
    /**
     * Episode thumbnail image
     */
    thumbnail?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenes".
 */
export interface Scene {
  id: string;
  /**
   * Parent project
   */
  project: string | Project;
  /**
   * Episode this scene belongs to
   */
  episode: string | Episode;
  /**
   * Scene number within the episode
   */
  sceneNumber: number;
  title: string;
  script?: {
    /**
     * Scene action and direction
     */
    action?: string | null;
    dialogue?:
      | {
          character: string | Character;
          /**
           * Character dialogue
           */
          lines: string;
          emotion?: ('neutral' | 'happy' | 'sad' | 'angry' | 'fearful' | 'surprised' | 'excited') | null;
          /**
           * Timing in seconds for this dialogue
           */
          timing?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Estimated scene duration in seconds
     */
    duration?: number | null;
  };
  storyboard?: {
    panels?:
      | {
          panelNumber: number;
          /**
           * Visual description of the panel
           */
          description?: string | null;
          image?: (string | null) | Media;
          cameraAngle?:
            | (
                | 'wide'
                | 'medium'
                | 'closeup'
                | 'extreme_closeup'
                | 'over_shoulder'
                | 'birds_eye'
                | 'low_angle'
                | 'high_angle'
              )
            | null;
          /**
           * Additional notes for this panel
           */
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Production status and assets
   */
  production: {
    status: 'pending' | 'generating' | 'reviewing' | 'approved' | 'failed';
    /**
     * Generated video for this scene
     */
    videoSegment?: (string | null) | Media;
    /**
     * Audio track for this scene
     */
    audioTrack?: (string | null) | Media;
    /**
     * Number of generation attempts
     */
    attempts?: number | null;
    lastAttempt?: string | null;
  };
  /**
   * Characters appearing in this scene
   */
  characters?: (string | Character)[] | null;
  /**
   * Scene location or setting
   */
  location?: string | null;
  timeOfDay?: ('dawn' | 'day' | 'dusk' | 'night') | null;
  /**
   * Overall mood or atmosphere of the scene
   */
  mood?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  /**
   * Type of task to be executed
   */
  taskType:
    | 'image_generation'
    | 'video_generation'
    | 'audio_generation'
    | 'script_generation'
    | 'embedding_generation'
    | 'scene_assembly';
  /**
   * Project this task belongs to
   */
  project: string | Project;
  /**
   * Related episode (if applicable)
   */
  episode?: (string | null) | Episode;
  /**
   * Related scene (if applicable)
   */
  scene?: (string | null) | Scene;
  /**
   * Related character (if applicable)
   */
  character?: (string | null) | Character;
  /**
   * Current task status
   */
  status: 'queued' | 'processing' | 'completed' | 'failed' | 'cancelled';
  /**
   * Task priority (1=lowest, 10=highest)
   */
  priority: number;
  input?: {
    /**
     * Prompt execution record for this task
     */
    prompt?: (string | null) | PromptsExecuted;
    /**
     * Task-specific input parameters
     */
    parameters?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Tasks that must complete before this one
     */
    dependencies?: (string | Task)[] | null;
  };
  output?: {
    /**
     * Generated media asset
     */
    media?: (string | null) | Media;
    /**
     * Task result data
     */
    result?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    metrics?: {
      /**
       * Processing time in seconds
       */
      processingTime?: number | null;
      /**
       * Cost in credits or currency
       */
      cost?: number | null;
      /**
       * AI tokens consumed
       */
      tokensUsed?: number | null;
    };
  };
  progress?: {
    /**
     * Progress percentage
     */
    percentage?: number | null;
    /**
     * Current processing step
     */
    currentStep?: string | null;
    /**
     * Estimated completion time
     */
    estimatedCompletion?: string | null;
  };
  error?: {
    /**
     * Error message
     */
    message?: string | null;
    /**
     * Error code
     */
    code?: string | null;
    /**
     * Number of retry attempts
     */
    retryCount?: number | null;
    /**
     * Timestamp of last retry
     */
    lastRetry?: string | null;
  };
  worker?: {
    /**
     * ID of the worker processing this task
     */
    workerId?: string | null;
    /**
     * When processing started
     */
    startedAt?: string | null;
    /**
     * Last heartbeat from worker
     */
    heartbeat?: string | null;
  };
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Execution records for audit
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts-executed".
 */
export interface PromptsExecuted {
  id: string;
  templateId?: (string | null) | PromptTemplate;
  app: string;
  feature?: string | null;
  stage: string;
  projectId?: string | null;
  tagsSnapshot?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  inputs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resolvedPrompt: string;
  model:
    | 'anthropic/claude-sonnet-4'
    | 'qwen/qwen3-vl-235b-a22b-thinking'
    | 'fal-ai/nano-banana'
    | 'fal-ai/nano-banana/edit';
  status: 'success' | 'error';
  outputRaw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates".
 */
export interface PromptTemplate {
  id: string;
  name: string;
  app: string;
  feature?: string | null;
  stage: string;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Template with placeholders like {{variableName}}
   */
  template: string;
  variableDefs: {
    name: string;
    type: 'string' | 'number' | 'boolean' | 'json' | 'text' | 'url';
    required?: boolean | null;
    description?: string | null;
    defaultValue?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  outputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  model:
    | 'anthropic/claude-sonnet-4'
    | 'qwen/qwen3-vl-235b-a22b-thinking'
    | 'fal-ai/nano-banana'
    | 'fal-ai/nano-banana/edit';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'characters';
        value: string | Character;
      } | null)
    | ({
        relationTo: 'episodes';
        value: string | Episode;
      } | null)
    | ({
        relationTo: 'scenes';
        value: string | Scene;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'prompt-templates';
        value: string | PromptTemplate;
      } | null)
    | ({
        relationTo: 'prompts-executed';
        value: string | PromptsExecuted;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  preferences?: T;
  subscription?:
    | T
    | {
        tier?: T;
        maxProjects?: T;
        maxEpisodesPerProject?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  project?: T;
  mediaType?: T;
  agentGenerated?: T;
  generationMetadata?:
    | T
    | {
        agentId?: T;
        promptUsed?: T;
        modelVersion?: T;
        generationTime?: T;
        taskId?: T;
      };
  embedding?: T;
  description?: T;
  tags?: T;
  relatedElements?:
    | T
    | {
        characters?: T;
        episode?: T;
        scene?: T;
        timestamp?: T;
      };
  technicalData?:
    | T
    | {
        duration?: T;
        resolution?: T;
        fps?: T;
        sampleRate?: T;
      };
  version?: T;
  status?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  genre?: T;
  episodeCount?: T;
  targetAudience?: T;
  status?: T;
  createdBy?: T;
  collaborators?: T;
  styleReferences?: T;
  projectSettings?:
    | T
    | {
        aspectRatio?: T;
        episodeDuration?: T;
        qualityTier?: T;
      };
  progress?:
    | T
    | {
        currentPhase?: T;
        completedSteps?: T;
        overallProgress?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  project?: T;
  user?: T;
  currentStep?: T;
  conversationHistory?: T;
  contextData?: T;
  awaitingUserInput?: T;
  lastChoices?: T;
  sessionState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  project?: T;
  name?: T;
  description?: T;
  profile?:
    | T
    | {
        age?: T;
        gender?: T;
        personality?: T;
        backstory?: T;
        motivations?: T;
        relationships?:
          | T
          | {
              character?: T;
              relationshipType?: T;
              description?: T;
              id?: T;
            };
      };
  visualDesign?:
    | T
    | {
        referenceImages?: T;
        finalDesign?: T;
        styleNotes?: T;
        colorPalette?: T;
      };
  voiceProfile?:
    | T
    | {
        voiceId?: T;
        audioSample?: T;
        voiceCharacteristics?: T;
      };
  appearances?:
    | T
    | {
        episode?: T;
        sceneIds?: T;
        screenTime?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  project?: T;
  episodeNumber?: T;
  title?: T;
  description?: T;
  synopsis?:
    | T
    | {
        logline?: T;
        summary?: T;
        themes?: T;
      };
  status?: T;
  script?:
    | T
    | {
        content?: T;
        version?: T;
        wordCount?: T;
        estimatedDuration?: T;
      };
  production?:
    | T
    | {
        sceneCount?: T;
        completedScenes?: T;
        renderProgress?: T;
      };
  metadata?:
    | T
    | {
        duration?: T;
        finalVideo?: T;
        thumbnail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenes_select".
 */
export interface ScenesSelect<T extends boolean = true> {
  project?: T;
  episode?: T;
  sceneNumber?: T;
  title?: T;
  script?:
    | T
    | {
        action?: T;
        dialogue?:
          | T
          | {
              character?: T;
              lines?: T;
              emotion?: T;
              timing?: T;
              id?: T;
            };
        duration?: T;
      };
  storyboard?:
    | T
    | {
        panels?:
          | T
          | {
              panelNumber?: T;
              description?: T;
              image?: T;
              cameraAngle?: T;
              notes?: T;
              id?: T;
            };
      };
  production?:
    | T
    | {
        status?: T;
        videoSegment?: T;
        audioTrack?: T;
        attempts?: T;
        lastAttempt?: T;
      };
  characters?: T;
  location?: T;
  timeOfDay?: T;
  mood?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  taskType?: T;
  project?: T;
  episode?: T;
  scene?: T;
  character?: T;
  status?: T;
  priority?: T;
  input?:
    | T
    | {
        prompt?: T;
        parameters?: T;
        dependencies?: T;
      };
  output?:
    | T
    | {
        media?: T;
        result?: T;
        metrics?:
          | T
          | {
              processingTime?: T;
              cost?: T;
              tokensUsed?: T;
            };
      };
  progress?:
    | T
    | {
        percentage?: T;
        currentStep?: T;
        estimatedCompletion?: T;
      };
  error?:
    | T
    | {
        message?: T;
        code?: T;
        retryCount?: T;
        lastRetry?: T;
      };
  worker?:
    | T
    | {
        workerId?: T;
        startedAt?: T;
        heartbeat?: T;
      };
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates_select".
 */
export interface PromptTemplatesSelect<T extends boolean = true> {
  name?: T;
  app?: T;
  feature?: T;
  stage?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  template?: T;
  variableDefs?:
    | T
    | {
        name?: T;
        type?: T;
        required?: T;
        description?: T;
        defaultValue?: T;
        id?: T;
      };
  outputSchema?: T;
  model?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts-executed_select".
 */
export interface PromptsExecutedSelect<T extends boolean = true> {
  templateId?: T;
  app?: T;
  feature?: T;
  stage?: T;
  projectId?: T;
  tagsSnapshot?:
    | T
    | {
        value?: T;
        id?: T;
      };
  inputs?: T;
  resolvedPrompt?: T;
  model?: T;
  status?: T;
  outputRaw?: T;
  errorMessage?: T;
  startedAt?: T;
  finishedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}